/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_failex_timesync_TimeSync */

#ifndef _Included_de_failex_timesync_TimeSync
#define _Included_de_failex_timesync_TimeSync
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_failex_timesync_TimeSync
 * Method:    setdate
 * Signature: (IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_de_failex_timesync_TimeSync_setdate
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
